#pragma once

#include <chrono>
#include <mutex>
#include <ostream>
#include <functional>
#include <vector>
#include <memory>
#include <mutex>
#include <ostream>
#include <type_traits>

namespace UCILoader {

    /*!
     * @brief Base interface for logging UCI protocol messages.
     * 
     * Provides an abstract interface for capturing messages exchanged with a chess engine
     * via the UCI protocol. The Logger is responsible for recording messages sent to the engine,
     * received from the engine, or generated by the parser.
     * 
     * @details
     * This is the core logging interface that all concrete loggers must inherit from.
     * Concrete implementations include file loggers, stream loggers, buffer loggers, and
     * callback-based loggers. Loggers can be customized using LoggerTraits to add behavior
     * such as timestamp formatting or filtering specific message types.
     * 
     * @see LoggerTrait for customizing logger behavior
     * @see LoggerBuilder for creating and composing loggers
     * @see Loggers namespace for factory functions
     */
    class Logger {
        public:
        /*!
         * @brief Enumeration of message directions for logging purposes.
         */
        enum MessageDirection {
            ToEngine,      ///< Message sent from the application to the chess engine
            FromEngine,    ///< Message received from the chess engine
            FromParser     ///< Message generated or parsed by the UCI parser
        };
        
        /*!
         * @brief Virtual destructor for proper cleanup of derived classes.
         */
        virtual ~Logger() = default;
        
        /*!
         * @brief Log a message with a specified direction.
         * 
         * @param dir The direction of the message (sent to engine, received from engine, or parsed)
         * @param msg The message content to be logged
         */
        virtual void log(MessageDirection dir, const std::string & msg) = 0;
    };
    
    /*!
     * @brief Base class for loggers that wrap and delegate to another logger.
     * 
     * This class provides a foundation for implementing the decorator pattern,
     * allowing composition of loggers and traits. Derived classes can intercept,
     * modify, or enhance logging behavior before delegating to the wrapped logger.
     */
    class LoggerWrapper : public Logger {
        std::unique_ptr<Logger> wrapped;
        protected:
        /*!
         * @brief Delegate a log message to the wrapped logger.
         * 
         * @param dir The message direction
         * @param msg The message to log
         */
        void delegate(MessageDirection dir, const std::string & msg);
        public:
        /*!
         * @brief Construct a LoggerWrapper with a logger to wrap.
         * 
         * @param logger The logger to wrap and delegate to
         */
        LoggerWrapper(std::unique_ptr<Logger> && logger);   
    };


    /*!
     * @brief Abstract base class for logger traits that customize logger behavior.
     * 
     * @details
     * The LoggerTrait mechanism provides a flexible way to add functionality to loggers
     * using the decorator pattern. Traits can be composed together to apply multiple
     * behaviors to a single logger.
     * 
     * Common use cases:
     * - Adding timestamps to log messages (Timestamp trait)
     * - Formatting messages for readability (Pretty trait)
     * - Filtering messages by direction (IgnoreParser, IgnoreEngine, IgnoreApplication traits)
     * 
     * @see LoggerBuilder for how to apply traits
     * @see LoggerTraits namespace for built-in trait implementations
     * 
     * Example usage with LoggerBuilder:
     * @code
     *     // Create a file logger with Pretty formatting and timestamps
     *     auto logger = Loggers::toFile("engine.log") | LoggerTraits::Pretty | LoggerTraits::Timestamp;
     * @endcode
     */
    class LoggerTrait {
        public:
        /*!
         * @brief Virtual destructor for proper cleanup of derived classes.
         */
        virtual ~LoggerTrait() = default;
        
        /*!
         * @brief Apply this trait to a logger by wrapping it.
         * 
         * Implementations should create a wrapper that applies the trait's behavior
         * to the provided logger.
         * 
         * @param logger The logger to apply this trait to
         * @return A new logger with this trait applied
         */
        virtual std::unique_ptr<Logger> addTo(std::unique_ptr<Logger> && logger) const = 0;
   };

    /*!
     * @brief Builder class for constructing and composing loggers with traits.
     * 
     * @details
     * LoggerBuilder provides a fluent interface for creating loggers with custom behavior.
     * Loggers are created using factory functions in the Loggers namespace, then
     * composed with traits using the pipe operator (|).
     * 
     * The builder uses the pipe operator for readability and to allow chaining multiple
     * trait applications. Once all traits are applied, call build() to obtain the final
     * logger instance.
     * 
     * @see Loggers namespace for factory functions
     * @see LoggerTraits namespace for available traits
     * 
     * Usage Examples:
     * @code
     *     // Simple file logger
     *     auto logger1 = Loggers::toFile("debug.log").build();
     *     
     *     // File logger with Pretty formatting
     *     auto logger2 = (Loggers::toFile("debug.log") | LoggerTraits::Pretty).build();
     *     
     *     // File logger with Pretty formatting and timestamps
     *     auto logger3 = (Loggers::toFile("debug.log") 
     *                     | LoggerTraits::Pretty 
     *                     | LoggerTraits::Timestamp).build();
     *     
     *     // Logger that ignores parser messages
     *     auto logger4 = (Loggers::toFile("engine.log") 
     *                     | LoggerTraits::IgnoreParser).build();
     * @endcode
     */
    class LoggerBuilder {
        std::unique_ptr<Logger> logger;
        public:
        /*!
         * @brief Construct a LoggerBuilder with a base logger.
         * 
         * @param base The base logger instance
         */
        LoggerBuilder(std::unique_ptr<Logger> && base);
        
        /*!
         * @brief Move constructor.
         * 
         * @param other The LoggerBuilder to move from
         */
        LoggerBuilder(LoggerBuilder && other);
        
        /*!
         * @brief Add a trait to customize the logger behavior.
         * 
         * This method applies a trait by wrapping the current logger.
         * Traits are applied in the order they are added.
         * 
         * @param trait The trait to add
         * @return Reference to this builder for method chaining
         */
        LoggerBuilder & addTrait(const LoggerTrait & trait);
        
        /*!
         * @brief Build and return the final logger instance.
         * 
         * @return A unique_ptr to the fully configured Logger
         */
        std::unique_ptr<Logger> build();

        /*!
         * @brief Operator overload for applying traits using pipe operator.
         * 
         * This allows fluent syntax using the | operator:
         * @code
         *     auto logger = Loggers::toFile("log.txt") | LoggerTraits::Pretty;
         * @endcode
         * 
         * @param builder The logger builder
         * @param trait The trait to apply
         * @return The modified builder
         */
        friend LoggerBuilder operator |(LoggerBuilder builder, const LoggerTrait & trait) {
            builder.addTrait(trait);
            return std::move(builder);
        };
    };

    class LogBuffer;

    /*!
     * @brief Factory functions for creating preconfigured loggers.
     * 
     * @details
     * The Loggers namespace provides factory methods for creating loggers with various
     * output destinations. Each factory returns a LoggerBuilder that can be customized
     * with LoggerTraits before calling build().
     * 
     * Factory Methods:
     * - toNoting(): Creates a logger that discards all messages
     * - toStd(): Logs to standard output (std::cout)
     * - toStderr(): Logs to standard error (std::cerr)
     * - toFile(): Logs to a file
     * - toBuffer(): Logs to an in-memory buffer
     * - toCallback(): Logs via a user-provided callback function
     * - toOstream(): Logs to an arbitrary std::ostream
     * - from<T>(): Creates a custom logger of type T
     * 
     * @see LoggerBuilder for composing multiple loggers with traits
     * @see LoggerTraits namespace for customization options
     * 
     * Usage Examples (from Examples/demo/main.cpp):
     * @code
     *     // Create a file logger with Pretty formatting
     *     auto logger = Loggers::toFile("Logs.txt") | LoggerTraits::Pretty;
     *     
     *     // Create a callback logger for custom handling
     *     auto logger = Loggers::toCallback([](Logger::MessageDirection dir, const std::string& msg) {
     *         std::cout << "Got message: " << msg << std::endl;
     *     });
     *     
     *     // Create a custom logger
     *     auto logger = Loggers::from<MyCustomLogger>(arg1, arg2);
     * @endcode
     */
    namespace Loggers {
        /*!
         * @brief Create a logger that discards all messages.
         * 
         * @return A LoggerBuilder for a no-operation logger
         */
        extern LoggerBuilder toNoting();
        
        /*!
         * @brief Create a logger that outputs to standard output.
         * 
         * @return A LoggerBuilder for a stdout logger
         */
        extern LoggerBuilder toStd();
        
        /*!
         * @brief Create a logger that outputs to standard error.
         * 
         * @return A LoggerBuilder for a stderr logger
         */
        extern LoggerBuilder toStderr();
        
        /*!
         * @brief Create a logger that outputs to a file.
         * 
         * @param filename Path to the log file
         * @return A LoggerBuilder for a file logger
         */
        extern LoggerBuilder toFile(const std::string & filename);
        
        /*!
         * @brief Create a logger that outputs to a file.
         * 
         * @param filename C-string path to the log file
         * @return A LoggerBuilder for a file logger
         */
        extern LoggerBuilder toFile(const char * filename);
        
        /*!
         * @brief Create a logger that stores messages in abuffer.
         * 
         * This is useful for capturing a snapshot of recent messages for debugging.
         * 
         * @param buffer Reference to the LogBuffer to store messages in
         * @return A LoggerBuilder for a buffer logger
         */
        extern LoggerBuilder toBuffer(LogBuffer & buffer); 
        
        /*!
         * @brief Create a logger that forwards all messages to a callback function.
         * 
         * This allows custom handling of log messages in your application.
         * 
         * @param callback Function to call for each logged message
         * @return A LoggerBuilder for a callback logger
         */
        extern LoggerBuilder toCallback(std::function<void(Logger::MessageDirection, const std::string & msg)> callback);
        
        /*!
         * @brief Create a logger that outputs to an arbitrary output stream.
         * 
         * @param os Reference to the output stream (e.g., std::cout, std::cerr, std::ofstream)
         * @return A LoggerBuilder for a stream logger
         */
        extern LoggerBuilder toOstream(std::ostream & os);

        /*!
         * @brief Create a custom logger of the specified type.
         * 
         * @tparam CustomLogger The custom logger class (must derive from Logger)
         * @tparam args Types of constructor arguments
         * @param params Constructor arguments for the custom logger
         * @return A LoggerBuilder for the custom logger
         * 
         * Example:
         * @code
         *     class MyLogger : public Logger {
         *         // ... implementation
         *     };
         *     
         *     auto logger = Loggers::from<MyLogger>(arg1, arg2).build();
         * @endcode
         */
        template <class CustomLogger, typename ... args>
        LoggerBuilder from(args... params) {
            static_assert((bool)std::is_base_of_v<Logger, CustomLogger>,
                      "CustomLogger must derive from Logger");
            auto logger = std::make_unique<CustomLogger>(params...);
            return LoggerBuilder(std::move(logger));
        };
    };

    /*!
     * @brief Predefined logger traits for common customizations.
     * 
     * @details
     * The LoggerTraits namespace provides ready-to-use traits that can be applied to loggers
     * to customize their behavior. Traits can be combined using the pipe operator with LoggerBuilder.
     * 
     * Available Traits:
     * - Pretty: Formats log messages for human readability
     * - IgnoreParser: Filters out messages from the parser (FromParser direction)
     * - IgnoreEngine: Filters out messages from the engine (FromEngine direction)
     * - IgnoreApplication: Filters out messages sent to the engine (ToEngine direction)
     * - Timestamp: Prepends timestamps to each log message
     * 
     * @see LoggerBuilder for how to apply traits
     * @see Loggers namespace for creating base loggers
     * 
     * Usage Examples:
     * @code
     *     // Log only engine messages with timestamps
     *     auto logger = (Loggers::toFile("engine.log") 
     *                    | LoggerTraits::IgnoreParser 
     *                    | LoggerTraits::IgnoreApplication
     *                    | LoggerTraits::Timestamp).build();
     *     
     *     // Pretty-formatted output with all messages
     *     auto logger = (Loggers::toStd() | LoggerTraits::Pretty).build();
     *     
     *     // As shown in Examples/demo/main.cpp:
     *     auto instance = ChessEngineInstanceBuilder->build(proces, 
     *                     Loggers::toFile("Logs.txt") | LoggerTraits::Pretty);
     * @endcode
     */
    namespace LoggerTraits {
        /*!
         * @brief Trait that formats log messages for human readability.
         * 
         * The Pretty trait enhances message formatting with clear direction indicators
         * and structured output suitable for reading log files or console output.
         */
        extern const LoggerTrait & Pretty;
        
        /*!
         * @brief Trait that filters out messages generated by the parser.
         * 
         * Messages with direction FromParser will be ignored.
         */
        extern const LoggerTrait & IgnoreParser;
        
        /*!
         * @brief Trait that filters out messages received from the engine.
         * 
         * Messages with direction FromEngine will be ignored.
         */
        extern const LoggerTrait & IgnoreEngine; 
        
        /*!
         * @brief Trait that filters out messages sent to the engine.
         * 
         * Messages with direction ToEngine will be ignored.
         */
        extern const LoggerTrait & IgnoreApplication;
        
        /*!
         * @brief Trait that prepends timestamps to all logged messages.
         * 
         * Useful for tracking the timing of UCI protocol exchanges.
         */
        extern const LoggerTrait & Timestamp;   
    };

    // Forward declaration of log buffer implementation details.
    /*!
     * @brief Private namespace containing internal LogBuffer implementation details.
     * 
     * This namespace provides implementation details that users should not directly access.
     */
    namespace _LogBufferPrivate {
        struct CriticalSection;
        class Friend;
    };

    /*!
     * @brief Thread-safe buffer for storing log messages.
     * 
     * @details
     * LogBuffer provides thread-safe storage of log messages in memory. It's useful for
     * capturing recent messages for debugging or diagnostics without writing to disk.
     * 
     * The buffer maintains a snapshot of logged messages that can be retrieved with
     * the snapshot() method.
     * 
     * Usage Example:
     * @code
     *     // Create a buffer for storing logs
     *     UCILoader::LogBuffer buffer;
     *     
     *     // Create a logger that stores messages in the buffer
     *     auto logger = Loggers::toBuffer(buffer).build();
     *     
     *     // ... perform operations that log messages ...
     *     
     *     // Get a snapshot of logged messages
     *     auto messages = buffer.snapshot();
     *     for (const auto& msg : messages) {
     *         std::cout << msg << std::endl;
     *     }
     * @endcode
     */
    class LogBuffer {
        std::shared_ptr<_LogBufferPrivate::CriticalSection> criticalSection;
        friend _LogBufferPrivate::Friend;
        public:
        /*!
         * @brief Add a message to the buffer.
         * 
         * @param msg The message string to add
         */
        void push_back(const std::string & msg);
        
        /*!
         * @brief Get a snapshot of all messages currently in the buffer.
         * 
         * @return A vector of log message strings
         */
        std::vector<std::string> snapshot() const;
    };

    namespace _LogBufferPrivate{
        /*!
         * @brief Internal critical section for thread-safe buffer operations.
         * 
         * @private Not for public use.
         */
        struct CriticalSection {
            std::mutex lock;
            std::vector<std::string> buffer;
        };
        
        /*!
         * @brief Friend class providing access to buffer internals.
         * 
         * @private Not for public use.
         */
        class Friend {
            protected:
            std::shared_ptr<CriticalSection> criticalSection;
            public:
            /*!
             * @brief Constructor granting internal access to LogBuffer.
             * 
             * @param buffer The LogBuffer to access
             */
            Friend(LogBuffer & buffer) {
                this->criticalSection = buffer.criticalSection;
            }
        };
    };
};